# Exercise 1.A NumPy: Manipulating Arrays 

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [3]:

for x in arrA:
    print(x * 2)


[22 24 26]
[28 30 32]


In [ ]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop works across the rows of the array, so entire rows are multiplied at once.
The second loop works through each individual value inside the rows.

In [5]:

for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

# This result is different because x represents the entire row array,
# not the individual value y.


[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [6]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [7]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [10]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]



This produces an error because the arrays have different shapes.
joined_array_1 has shape (4,3) while joined_array_2 has shape (2,6)
stacked_array_2 = np.stack((joined_array_1, joined_array_2))


In [9]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)


[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]



This creates an error because the arrays do not have the same
number of rows when concatenating on axis=1.
another_2 = np.concatenate((joined_array_1, arrA), axis=1)


In [11]:

horizontal_stack = np.hstack((arrA, arrA))
# hstack joins arrays horizontally by columns
print(horizontal_stack)

vertical_stack = np.vstack((arrA, arrA))
# vstack joins arrays vertically by rows
print(vertical_stack)

depth_stack = np.dstack((arrA, arrA))
# dstack stacks arrays by depth
print(depth_stack)


[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splittin Arrays

In [12]:

splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

# Result: 2 arrays, each with 2 dimensions.


[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [13]:

spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

# Result: 3 arrays with uneven row distribution.


[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [14]:

result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)


[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [15]:

arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)


[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [16]:

print(arrB)

z = arrB < 7
arrC = arrB[z]

print(arrC)


[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [17]:

y = arrB >= 7
arrD = arrB[y]

print(arrD)


[ 7 13  7]
