# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 20, size=2)
print(r_1)

[ 1 16]


In [3]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[15  4]]


In [4]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.99883671]
 [0.72953055]]


In [ ]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

In [ ]:
r_5 = np.random.rand(4, 5)
print(r_5)

## Generating Random Choices from an Array

In [7]:

students = np.array([
    'Alex', 'Jordan', 'Taylor', 'Morgan',
    'Casey', 'Riley', 'Avery', 'Jamie',
    'Cameron', 'Parker', 'Quinn', 'Skyler'
])

In [8]:
call_on = np.random.choice(students)
print(call_on)

Skyler


In [9]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)

# This may not be effective because some students can appear
# more than once while others may not appear at all.


[['Riley' 'Alex' 'Skyler' 'Jamie']
 ['Avery' 'Skyler' 'Quinn' 'Taylor']
 ['Parker' 'Jordan' 'Casey' 'Jordan']]


In [10]:
probabilities = [0.30, 0.10, 0.10, 0.05, 0.10, 0.05,
                 0.10, 0.05, 0.05, 0.05, 0.05, 0.00]

call_on_weighted = np.random.choice(
    students,
    size=5,
    p=probabilities
)

print(call_on_weighted)

# Alex has a 30% chance.
# Skyler has a 0% chance.
# Other students have smaller probabilities.


['Alex' 'Parker' 'Taylor' 'Casey' 'Alex']


## Generating a Normal Distribution

In [11]:

bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)


[[-3.89875859 11.32247162 10.32719371  7.7970648  10.92866872]
 [ 1.55719108  2.20074935 15.40325131  4.33819977 14.33083978]
 [-2.35853009 12.15516703 11.02006861 11.3770195  12.17149881]
 [10.24693761  5.72332364 13.96739784  8.54326007 13.11344568]]
