# Exercise 1.C Performing Operations on Arrays

In [1]:

import numpy as np


## Sample Arrays

In [2]:

r_1 = np.random.randint(1, 20, size=2)
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.rand(4, 5)


## Permutations

In [3]:

print(r_4)


[[53 57 52 99 95]
 [76 31 58 78 66]
 [83 87 72 73 81]
 [70 45 85 30 88]]


In [4]:

np.random.shuffle(r_4)
print(r_4)


[[70 45 85 30 88]
 [83 87 72 73 81]
 [76 31 58 78 66]
 [53 57 52 99 95]]


shuffle changes the original array order directly.

In [5]:

new_shuffle = np.random.permutation(r_4)

print(new_shuffle)
print(r_4)


[[70 45 85 30 88]
 [53 57 52 99 95]
 [76 31 58 78 66]
 [83 87 72 73 81]]
[[70 45 85 30 88]
 [83 87 72 73 81]
 [76 31 58 78 66]
 [53 57 52 99 95]]


shuffle modifies the original array, while permutation returns a shuffled copy.

## Mathematical Operations

In [6]:

print(r_1, r_1.shape)
print(r_2, r_2.shape)

result = np.add(r_1, r_2)
print(result)
print(result.shape)


[10  4] (2,)
[[ 1 13]] (1, 2)
[[11 17]]
(1, 2)


In [7]:

print(r_1, r_1.shape)
print(r_3, r_3.shape)

result = np.add(r_1, r_3)
print(result)
print(result.shape)


[10  4] (2,)
[[0.32785426]
 [0.21997154]] (2, 1)
[[10.32785426  4.32785426]
 [10.21997154  4.21997154]]
(2, 2)


In [34]:

print(r_2, r_2.shape)
print(r_4, r_4.shape)

result = np.add(r_2, r_4)
print(result)
print(result.shape)


[[ 1 13]] (1, 2)
[[70 45 85 30 88]
 [83 87 72 73 81]
 [76 31 58 78 66]
 [53 57 52 99 95]] (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [11]:

# This produces a broadcasting error because the shapes are incompatible.

# np.add(r_1, r_4)

print(np.add(r_2, r_4))
print(np.add(r_3, r_4))


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [12]:

print(np.add(np.array([1]), r_4))


[[ 71  46  86  31  89]
 [ 84  88  73  74  82]
 [ 77  32  59  79  67]
 [ 54  58  53 100  96]]


In [13]:

print(np.add(np.array([[1]]), r_4))


[[ 71  46  86  31  89]
 [ 84  88  73  74  82]
 [ 77  32  59  79  67]
 [ 54  58  53 100  96]]


In [14]:

print(np.add(np.array([1,1,1,1,1]), r_4))


[[ 71  46  86  31  89]
 [ 84  88  73  74  82]
 [ 77  32  59  79  67]
 [ 54  58  53 100  96]]


In [15]:

# This creates a broadcasting error because the dimensions do not align.

# print(np.add(np.array([[1],[1]]), r_4))



Broadcasting allows NumPy to perform operations on arrays with different shapes.
Smaller arrays are expanded automatically when dimensions are compatible.
The resulting shape is based on the larger compatible array.


## Rounding

In [16]:

print(r_3)


[[0.32785426]
 [0.21997154]]


In [17]:

print(np.trunc(r_3))


[[0.]
 [0.]]


In [18]:

print(np.fix(r_3))


[[0.]
 [0.]]


In [19]:

print(np.floor(r_3))


[[0.]
 [0.]]


In [20]:

print(np.ceil(r_3))


[[1.]
 [1.]]


In [21]:

print(np.round(r_3, 2))


[[0.33]
 [0.22]]


## Cumulative Operations

In [22]:

print(r_4)


[[70 45 85 30 88]
 [83 87 72 73 81]
 [76 31 58 78 66]
 [53 57 52 99 95]]


In [23]:

print(np.sum(r_4))


1379


In [24]:

print(np.sum(r_4, axis=0))


[282 220 267 280 330]


In [25]:

print(np.sum(r_4, axis=1))


[318 396 309 356]


In [26]:

print(np.cumsum(r_4))


[  70  115  200  230  318  401  488  560  633  714  790  821  879  957
 1023 1076 1133 1185 1284 1379]


In [27]:

print(np.cumsum(r_4, axis=0))


[[ 70  45  85  30  88]
 [153 132 157 103 169]
 [229 163 215 181 235]
 [282 220 267 280 330]]


## Grocery Problem

In [28]:

bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)


[2 3 4 0]
[4 0 1 2]


In [29]:

print(f"The first bag contains {np.sum(bag1)} items.")
print(f"The second bag contains {np.sum(bag2)} items.")


The first bag contains 9 items.
The second bag contains 7 items.


In [30]:

totals = np.add(bag1, bag2)

print(f"There are {totals[0]} vegetables, {totals[1]} fruits, "
      f"{totals[2]} boxes of snacks, and {totals[3]} beverages.")


There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages.


## Teamwork

In [31]:

ali = np.array([5, 4, 6, 4, 2])
ben = np.array([0, 5, 5, 3, 4])
carla = np.array([3, 6, 0, 3, 4])

all_knocks = np.array([ali, ben, carla])
print(all_knocks)


[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [32]:

person_totals = np.sum(all_knocks, axis=1)
group_total = np.sum(all_knocks)

print(person_totals)
print(group_total)


[21 17 16]
54


In [33]:

daily_totals = np.sum(all_knocks, axis=0)
rolling_total = np.cumsum(daily_totals)
estimated_votes = rolling_total * 0.5

print(estimated_votes)


[ 4.  11.5 17.  22.  27. ]
